// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://orxjqvpjseuormxpipbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeGpxdnBqc2V1b3JteHBpcGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MzY2NTMsImV4cCI6MjA4NzAxMjY1M30.bemSfgOgJULnueuGaYiCK1cbkR3nNdI2KqFkX8SeWuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Liste des emails autorisés en tant que Super Admin
const SUPER_ADMIN_EMAILS = [
  "ramatayaha003@gmail.com",
  "kissima99@gmail.com" // Ajouté par précaution
];

export async function isCurrentUserAdmin() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return false;

  if (user.email && SUPER_ADMIN_EMAILS.includes(user.email.toLowerCase())) return true;

  const { data, error } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();

  if (error || !data) return false;
  return data.role === 'admin' || data.role === 'super_admin';
}

export async function isCurrentUserSuperAdmin() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    console.log("[Auth] Aucun utilisateur connecté");
    return false;
  }

  const userEmail = user.email?.toLowerCase();
  console.log("[Auth] Vérification Super Admin pour:", userEmail);

  // Vérification par email (prioritaire)
  if (userEmail && SUPER_ADMIN_EMAILS.includes(userEmail)) {
    console.log("[Auth] Accès accordé par email");
    return true;
  }

  // Vérification par base de données
  const { data, error } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();

  if (error) {
    console.error("[Auth] Erreur lors de la vérification du profil:", error);
    return false;
  }

  const isSuper = data?.role === 'super_admin';
  console.log("[Auth] Accès base de données:", isSuper ? "OUI" : "NON");
  return isSuper;
}