// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://orxjqvpjseuormxpipbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeGpxdnBqc2V1b3JteHBpcGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MzY2NTMsImV4cCI6MjA4NzAxMjY1M30.bemSfgOgJULnueuGaYiCK1cbkR3nNdI2KqFkX8SeWuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

const SUPER_ADMIN_EMAILS = ["ramatayaha003@gmail.com"];

export async function isCurrentUserAdmin() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return false;

  // Check email first for immediate access
  if (user.email && SUPER_ADMIN_EMAILS.includes(user.email)) return true;

  const { data, error } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();

  if (error || !data) return false;
  return data.role === 'admin' || data.role === 'super_admin';
}

export async function isCurrentUserSuperAdmin() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return false;

  // Check email first for immediate access
  if (user.email && SUPER_ADMIN_EMAILS.includes(user.email)) return true;

  const { data, error } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();

  if (error || !data) return false;
  return data.role === 'super_admin';
}